/**
 * Regenerates the Multiplier2 circuit fixtures. Run manually (never in CI):
 *
 *   CIRCOM=/path/to/circom bun test/fixtures/generate.ts
 *
 * Requires the circom 2.x compiler binary (https://github.com/iden3/circom/releases)
 * on the PATH or pointed at by $CIRCOM; everything else (powers-of-tau
 * ceremony, Groth16 setup, verifier export/compile, sample proof) runs
 * through the snarkjs JS API and solc-js via bunx.
 *
 * The trusted setup here is DEV-ONLY: the ceremony entropy is a fixed
 * string committed below, so proofs from these artifacts must never guard
 * anything real. That is fine for fixtures — the tests only assert that
 * proving and on-chain verification round-trip.
 */
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const CIRCUIT_SOURCE = `pragma circom 2.0.0;

template Multiplier2() {
    signal input a;
    signal input b;
    signal output c;
    c <== a * b;
}

component main = Multiplier2();
`;

const PTAU_POWER = 8;
const ENTROPY = "evmcrispr zk module fixture entropy (dev-only setup)";
const SAMPLE_INPUTS = { a: 3, b: 11 };

const here = dirname(fileURLToPath(import.meta.url));
const work = mkdtempSync(join(tmpdir(), "zk-fixtures-"));
const circom = process.env.CIRCOM ?? "circom";

// 1. Compile the circuit.
const circomVersion = execFileSync(circom, ["--version"]).toString().trim();
writeFileSync(join(work, "multiplier2.circom"), CIRCUIT_SOURCE);
execFileSync(circom, ["multiplier2.circom", "--r1cs", "--wasm"], {
  cwd: work,
});
const wasmPath = join(work, "multiplier2_js", "multiplier2.wasm");
const r1csPath = join(work, "multiplier2.r1cs");

// 2. Dev powers-of-tau ceremony + Groth16 setup.
const { curves, groth16, powersOfTau, zKey } = await import("snarkjs");
// ffjavascript's worker pool crashes under bun — build the curve
// single-threaded and pre-seed the global cache so every snarkjs-internal
// buildBn128() call reuses it.
const bn128 = await curves.getCurveFromName("bn128", { singleThread: true });
(globalThis as Record<string, unknown>).curve_bn128 = bn128;
const ptau0 = join(work, "pot0.ptau");
const ptau1 = join(work, "pot1.ptau");
const ptauFinal = join(work, "pot_final.ptau");
const zkey0 = join(work, "multiplier2_0.zkey");
const zkeyFinal = join(work, "multiplier2_final.zkey");
await powersOfTau.newAccumulator(bn128, PTAU_POWER, ptau0);
await powersOfTau.contribute(ptau0, ptau1, "zk fixture", ENTROPY);
await powersOfTau.preparePhase2(ptau1, ptauFinal);
await zKey.newZKey(r1csPath, ptauFinal, zkey0);
await zKey.contribute(zkey0, zkeyFinal, "zk fixture", ENTROPY);

// 3. Export + compile the Solidity verifier.
const template = readFileSync(
  join(here, "../../node_modules/snarkjs/templates/verifier_groth16.sol.ejs"),
  "utf8",
);
const verifierSource: string = await zKey.exportSolidityVerifier(zkeyFinal, {
  groth16: template,
});
const solcVersion = "0.8.26";
const { compileCached } = await import(
  "../../../contracts/src/utils/solcLoader"
);
const { bytecode: verifierBytecode, compilerLongVersion } = await compileCached(
  verifierSource,
  [`version:${solcVersion}`],
  {
    log: (m: string) => console.log(m),
  },
);
console.log(`verifier compiled with solc ${compilerLongVersion}`);

// 4. Sample proof for the unit tests (same shape zk:prove binds).
const { proof, publicSignals } = await groth16.fullProve(
  SAMPLE_INPUTS,
  wasmPath,
  zkeyFinal,
);
const cannedProof = JSON.stringify({ proof, publicSignals });

// 5. Emit the fixture modules.
const wasmB64 = readFileSync(wasmPath).toString("base64");
const zkeyB64 = readFileSync(zkeyFinal).toString("base64");
const provenance = `// Auto-generated by generate.ts — do not edit by hand; rerun the script to
// regenerate. Provenance: ${circomVersion}; snarkjs JS API dev ceremony
// (bn128, power ${PTAU_POWER}, fixed entropy — DEV-ONLY setup, see generate.ts).`;

writeFileSync(
  join(here, "multiplier2.ts"),
  `${provenance}
//
// Circuit source:
//
${CIRCUIT_SOURCE.trimEnd()
  .split("\n")
  .map((l) => `//   ${l}`.trimEnd())
  .join("\n")}

/** multiplier2_js/multiplier2.wasm (witness generator), base64. */
export const MULTIPLIER2_WASM_B64 = "${wasmB64}";

/** multiplier2_final.zkey (Groth16 proving key, dev setup), base64. */
export const MULTIPLIER2_ZKEY_B64 = "${zkeyB64}";
`,
);

writeFileSync(
  join(here, "multiplier2-verifier.ts"),
  `${provenance}
// Compiled with solc ${solcVersion} (optimizer on, 200 runs, via the
// contracts-module solc loader) from the snarkjs-exported verifier below:
//
${verifierSource
  .trimEnd()
  .split("\n")
  .map((l) => `//   ${l}`.trimEnd())
  .join("\n")}

/** Creation bytecode of the Groth16Verifier contract above. */
export const MULTIPLIER2_VERIFIER_BYTECODE = "${verifierBytecode}";
`,
);

writeFileSync(
  join(here, "canned-proof.ts"),
  `${provenance}
// A real snarkjs groth16.fullProve output for inputs a=3, b=11 (c=33),
// exactly as zk:prove binds it. Proof bytes are randomized per proving
// run — tests must never pin them, only structure and public signals.

export const CANNED_PROOF_JSON = ${JSON.stringify(cannedProof)};
`,
);

console.log(`fixtures written from ${work}`);

await bn128.terminate();
