/**
 * Regenerates the pinned test vectors. Run manually:
 *
 *   bun test/fixtures/generate.ts
 *
 * Everything derives from @zk-kit primitives (via the circom module) and the
 * standard anvil test mnemonic, so the vectors are stable — they only
 * change if the identity scheme or IDENTITY_MESSAGE changes, which must
 * never happen silently (it would rotate every wallet-derived identity).
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { privateKeyToAccount } from "viem/accounts";
import { deriveIdentity, IDENTITY_MESSAGE } from "../../src/utils/identity";
import { hashSignal, parseSignalValue } from "../../src/utils/proof";

// Anvil account #0 (standard `test test … junk` mnemonic).
const ANVIL_KEY_0 =
  "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";

const account = privateKeyToAccount(ANVIL_KEY_0);
const signature = await account.signMessage({ message: IDENTITY_MESSAGE });
const walletIdentity = await deriveIdentity(signature);
const seedIdentity = await deriveIdentity("test seed");

const out = `// Auto-generated by generate.ts — do not edit by hand.

/** personal_sign(IDENTITY_MESSAGE) of anvil account #0. */
export const ANVIL0_SIGNATURE = "${signature}";

/** Identity commitment derived from that signature. */
export const ANVIL0_COMMITMENT =
  ${walletIdentity.commitment}n;

/** Identity commitment of the literal seed "test seed". */
export const TEST_SEED_COMMITMENT =
  ${seedIdentity.commitment}n;
export const TEST_SEED_SECRET_SCALAR =
  ${seedIdentity.secretScalar}n;

/** hashSignal(42) — keccak256(uint256 42) >> 8. */
export const HASHED_42 =
  ${hashSignal(42n)}n;

/** parseSignalValue("test-poll") — UTF-8 bytes as a bigint. */
export const TEXT_SIGNAL_TEST_POLL =
  ${parseSignalValue("test-poll", "scope")}n;
`;

writeFileSync(join(dirname(fileURLToPath(import.meta.url)), "vectors.ts"), out);
console.log("vectors written");
