/**
 * Regenerates the assert-circuit fixtures. Run manually (never in CI):
 *
 *   bun test/fixtures/generate.ts
 *
 * Unlike the zk module there is no external toolchain: the Noir compiler
 * and Barretenberg both ship in the npm dependencies, so everything runs
 * through the module's own utils. UltraHonk needs no trusted setup — the
 * artifact and proof are fully reproducible up to proof randomness.
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { proveUltraHonk } from "../../src/utils/barretenberg";
import { compileNoirCached } from "../../src/utils/noir";
import { ASSERT_SOURCE } from "../fixtures";

const here = dirname(fileURLToPath(import.meta.url));
const log = (m: string) => console.log(m);

const compiled = await compileNoirCached(ASSERT_SOURCE, { log });
const proof = await proveUltraHonk(
  compiled.compileKey,
  compiled.program,
  { x: "3", y: "5" },
  "keccak",
  { log },
);

const provenance = `// Auto-generated by generate.ts — do not edit by hand; rerun the script to
// regenerate. Provenance: noir ${compiled.program.noir_version}, UltraHonk keccak transcript.`;

writeFileSync(
  join(here, "assert-circuit.ts"),
  `${provenance}
//
// Circuit source (test/fixtures.ts ASSERT_SOURCE):
//
${ASSERT_SOURCE.trimEnd()
  .split("\n")
  .map((l) => `//   ${l}`.trimEnd())
  .join("\n")}

/** Compiled program artifact JSON (@noir:compile output shape). */
export const ASSERT_ARTIFACT_JSON = ${JSON.stringify(compiled.artifactJson)};

/** A real keccak UltraHonk proof for inputs x=3, y=5, exactly as
 * noir:prove binds it. Proof bytes are randomized per proving run —
 * tests must never pin them, only structure and public inputs. */
export const CANNED_PROOF_JSON = ${JSON.stringify(JSON.stringify(proof))};
`,
);

console.log("fixtures written");
process.exit(0);
