#!/usr/bin/env bun
/**
 * Regenerate src/utils/solcHashes.ts: the sha256 of every solc release
 * build, read from binaries.soliditylang.org's list.json and pinned into
 * the repo. At runtime downloaded soljson builds are verified against this
 * map, so the repo (audited at generation time) is the trust root rather
 * than whatever the binaries host serves later.
 *
 * Run after a new solc release: bun scripts/generate-solc-hashes.ts
 */
import { join } from "node:path";

const LIST_URL = "https://binaries.soliditylang.org/bin/list.json";

interface Build {
  path: string;
  sha256?: string;
  prerelease?: string;
}

const res = await fetch(LIST_URL);
if (!res.ok) throw new Error(`${res.status} fetching ${LIST_URL}`);
const list = (await res.json()) as {
  builds: Build[];
  releases: Record<string, string>;
};

const releaseFiles = new Set(Object.values(list.releases));
const entries: [string, string][] = [];
for (const build of list.builds) {
  if (!releaseFiles.has(build.path)) continue; // skip nightlies
  const m = build.path.match(/^soljson-v(.+)\.js$/);
  if (!m) continue;
  if (!build.sha256) throw new Error(`no sha256 for ${build.path}`);
  entries.push([m[1], build.sha256]);
}
if (entries.length < 100) {
  throw new Error(`suspiciously few releases (${entries.length})`);
}

const body = entries
  .map(([longVersion, sha256]) => `  "${longVersion}": "${sha256}",`)
  .join("\n");
const out = `// AUTO-GENERATED by scripts/generate-solc-hashes.ts — do not edit.
// sha256 of every solc release build (binaries.soliditylang.org list.json),
// pinned into the repo so downloaded compilers are verified against hashes
// audited at generation time rather than whatever the host serves later.

/** long version → 0x-prefixed sha256 of the soljson build. */
export const SOLC_SHA256: Record<string, string> = {
${body}
};
`;

const target = join(import.meta.dirname, "../src/utils/solcHashes.ts");
await Bun.write(target, out);
console.log(`wrote ${entries.length} release hashes to ${target}`);
