// Generated by scripts/sync-smart-dependency-hashes.ts.

import type { Address, Hex } from "viem";
import {
  COLLECTIONS_ADDRESS,
  CORE_ADDRESS,
  EXPRESSIONS_ADDRESS,
  OPERATIONS_ADDRESS,
} from "./addresses";
export const SMART_DEPENDENCY_HASHES: Record<Address, Hex> = {
  [CORE_ADDRESS.toLowerCase() as Address]:
    "0xe4162ec2aa7faa9a57a6ab435f18367331cf117c192d77aa8fa99ad8717bb6f9",
  [OPERATIONS_ADDRESS.toLowerCase() as Address]:
    "0x2c23246eb4c01287f15a214cd8ddf7f6a42b1de3e743e13f937f68aba428d3de",
  [COLLECTIONS_ADDRESS.toLowerCase() as Address]:
    "0x3a2eebe43e41777377eefcf10f1a9011658e887230a3913dbfcfec4f37cde7b0",
  [EXPRESSIONS_ADDRESS.toLowerCase() as Address]:
    "0x51220263dc89a206c3b561c006308ff4b87caf6b97492443286093191b625c11",
};
