// Generated by scripts/sync-smart-dependency-hashes.ts.

import type { Address, Hex } from "viem";
import {
  COLLECTIONS_ADDRESS,
  CORE_ADDRESS,
  EXPRESSIONS_ADDRESS,
  OPERATIONS_ADDRESS,
} from "./addresses";
export const SMART_DEPENDENCY_HASHES: Record<Address, Hex> = {
  [CORE_ADDRESS.toLowerCase() as Address]:
    "0xaf0c541f7755865eaa177c92ad041e88258766457fa02dc81406c5e8f76f7feb",
  [OPERATIONS_ADDRESS.toLowerCase() as Address]:
    "0x7e8b97fb2bdc86551d58dfce2e50c2a35e57b0ed734cf540f2eec7ffdb09fbc1",
  [COLLECTIONS_ADDRESS.toLowerCase() as Address]:
    "0x7287bccb153c694f843f46f91a095fee3f023d8aa0b9be6fc6c58197e6b9efcb",
  [EXPRESSIONS_ADDRESS.toLowerCase() as Address]:
    "0x3c52e3025fa1bed7fa34edb206ccf09b24876d61e0b86c37728f3f5d29a3d739",
};
