import { Module } from "../Module";
import type {
  CommandImportMap,
  Commands,
  HelperArgDefEntry,
  HelperFunctions,
  HelperImportMap,
  IModuleConstructor,
  ModuleContext,
} from "../types";
import { registerChains } from "./chains";
import { isExperimentalEnabled } from "./experimental";
import type { ArgType, ChainDef, ConfigDef, CustomArgTypes } from "./schema";

/**
 * Create a module class with the given name, commands, and helpers.
 */
function createModuleClass<M extends Module>(
  name: string,
  commands: Commands<M>,
  helpers: HelperFunctions<M>,
  helperReturnTypes: Record<string, ArgType>,
  helperHasArgs: Record<string, boolean>,
  helperArgDefs: Record<string, HelperArgDefEntry[]>,
  helperDescriptions: Record<string, string>,
  commandDescriptions: Record<string, string>,
  types: CustomArgTypes = {},
  constants: Record<string, string> = {},
  configs: ConfigDef[] = [],
  experimentalCommands: string[] = [],
  experimentalHelpers: string[] = [],
  helperOnchain: Record<string, boolean> = {},
  helperBatchable: Record<string, boolean> = {},
): IModuleConstructor {
  return class extends Module {
    static readonly moduleName = name;

    constructor(context: ModuleContext) {
      super(
        name,
        commands,
        helpers,
        helperReturnTypes,
        helperHasArgs,
        helperArgDefs,
        helperDescriptions,
        commandDescriptions,
        constants,
        types,
        context,
        configs,
        experimentalCommands,
        experimentalHelpers,
        helperOnchain,
        helperBatchable,
      );
    }
  } as IModuleConstructor;
}

/**
 * All-in-one factory for modules.
 *
 * Accepts typed import maps (generated by codegen) and wraps each entry
 * into a lazy loader that resolves the default export.
 *
 * Experimental entries are omitted from the command/helper maps when
 * `VITE_PUBLIC_EXPERIMENTAL` is not enabled; their names are kept in
 * `experimentalCommands`/`experimentalHelpers` so the interpreter and
 * analyzer can report a dedicated error instead of "unknown". The env is
 * read once at module-definition time (import time).
 *
 * @example
 * ```ts
 * import { commands, helpers } from "./_generated";
 *
 * export class MyModule extends defineModule("mymod", commands, helpers) {}
 * ```
 */
export function defineModule(
  name: string,
  commandImports: CommandImportMap,
  helperImports?: HelperImportMap,
  types?: CustomArgTypes,
  constants?: Record<string, string>,
  configs?: ConfigDef[],
  chains?: ChainDef[],
): IModuleConstructor {
  // Chains a module ships become usable (`switch <id>`) as soon as the
  // module class exists, even before any of its commands load.
  if (chains?.length) registerChains(...chains);
  const experimentalOn = isExperimentalEnabled();
  const experimentalCommands: string[] = [];
  const experimentalHelpers: string[] = [];

  const commands: Commands = {};
  const commandDescriptions: Record<string, string> = {};
  for (const [k, entry] of Object.entries(commandImports)) {
    if (entry.experimental && !experimentalOn) {
      experimentalCommands.push(k);
      continue;
    }
    commands[k] = () => entry.load().then((m) => m.default);
    if (entry.description) {
      commandDescriptions[k] = entry.description;
    }
  }

  const helpers: HelperFunctions = {};
  const helperReturnTypes: Record<string, ArgType> = {};
  const helperHasArgs: Record<string, boolean> = {};
  const helperArgDefsMap: Record<string, HelperArgDefEntry[]> = {};
  const helperDescriptions: Record<string, string> = {};
  const helperOnchain: Record<string, boolean> = {};
  const helperBatchable: Record<string, boolean> = {};
  if (helperImports) {
    for (const [k, entry] of Object.entries(helperImports)) {
      if (entry.experimental && !experimentalOn) {
        experimentalHelpers.push(k);
        continue;
      }
      helpers[k] = () => entry.load().then((m) => m.default);
      if (entry.onchain) {
        helperOnchain[k] = true;
      }
      if (entry.batchable !== undefined) {
        helperBatchable[k] = entry.batchable;
      }
      if (entry.returnType) {
        helperReturnTypes[k] = entry.returnType;
      }
      if (entry.hasArgs !== undefined) {
        helperHasArgs[k] = entry.hasArgs;
      }
      if (entry.argDefs) {
        helperArgDefsMap[k] = entry.argDefs;
      }
      if (entry.description) {
        helperDescriptions[k] = entry.description;
      }
    }
  }

  return createModuleClass(
    name,
    commands,
    helpers,
    helperReturnTypes,
    helperHasArgs,
    helperArgDefsMap,
    helperDescriptions,
    commandDescriptions,
    types ?? {},
    constants ?? {},
    configs ?? [],
    experimentalCommands,
    experimentalHelpers,
    helperOnchain,
    helperBatchable,
  );
}
