// AUTO-GENERATED by scripts/publish-runner.ts — do not edit by hand.
// Regenerate with: bun run publish-runner (in modules/gelato)

/** CID of the EVML runner in Gelato's function store, "" until published. */
export const RUNNER_CID = "";
/** sha256 of the published archive, to skip re-uploading identical bytes. */
export const RUNNER_SHA256 = "";
/** @evmcrispr/module-gelato version the runner was built from. */
export const RUNNER_VERSION = "";
/** Size of the published archive in bytes. */
export const RUNNER_BUNDLE_BYTES = 0;

/** The runner CID to schedule with: EVMCRISPR_RUNNER_CID overrides the
 *  published one (tests, staging a new build before regenerating). */
export function runnerCid(): string {
  const env =
    typeof process !== "undefined"
      ? process.env?.EVMCRISPR_RUNNER_CID
      : undefined;
  return env || RUNNER_CID;
}
