#!/usr/bin/env bun
/**
 * Code-generation script for EVMcrispr modules.
 *
 * Scans `src/commands/` and `src/helpers/` in the current working directory
 * and generates `src/_generated.ts` with typed, static import maps.
 *
 * Usage: bun codegen.ts [srcDir]
 *   srcDir defaults to ./src
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const srcDir = process.argv[2] || "./src";
const commandsDir = join(srcDir, "commands");
const helpersDir = join(srcDir, "helpers");

function getNames(dir: string): string[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(".ts") && !f.startsWith("_"))
    .map((f) => f.replace(/\.ts$/, ""))
    .sort();
}

const commandNames = getNames(commandsDir);
const helperNames = getNames(helpersDir);

const lines: string[] = [
  "// WARNING: this file is auto-generated by codegen. Do not edit.",
];

const imports: string[] = [];
if (commandNames.length > 0) imports.push("CommandImportMap");
if (helperNames.length > 0) imports.push("HelperImportMap");

if (imports.length > 0) {
  lines.push(`import type { ${imports.join(", ")} } from "@evmcrispr/sdk";`);
}

lines.push("");

if (commandNames.length > 0) {
  lines.push("export const commands: CommandImportMap = {");
  for (const name of commandNames) {
    lines.push(
      `  ${JSON.stringify(name)}: () => import("./commands/${name}"),`,
    );
  }
  lines.push("};");
} else {
  lines.push("export const commands = {};");
}

lines.push("");

if (helperNames.length > 0) {
  lines.push("export const helpers: HelperImportMap = {");
  for (const name of helperNames) {
    lines.push(`  ${JSON.stringify(name)}: () => import("./helpers/${name}"),`);
  }
  lines.push("};");
} else {
  lines.push("export const helpers = {};");
}

lines.push(""); // trailing newline

const outPath = join(srcDir, "_generated.ts");
const content = lines.join("\n");

// Only write if content actually changed to avoid unnecessary filesystem events
// that trigger turbo watch / bun build --watch cascades.
if (!existsSync(outPath) || readFileSync(outPath, "utf-8") !== content) {
  writeFileSync(outPath, content);
  console.log(`codegen: wrote ${outPath}`);
} else {
  console.log(`codegen: ${outPath} up to date`);
}
