#!/usr/bin/env bun
/**
 * Generates src/_generated.ts (module registry) from this package's own
 * dependencies, so the registry can never drift from package.json.
 * The dependency list itself is kept in sync with the modules/ directory
 * by scripts/sync-modules.ts at the repo root.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { sortModuleNames } from "../src/order";

const PREFIX = "@evmcrispr/module-";
const pkgDir = resolve(import.meta.dirname, "..");
const pkg = JSON.parse(readFileSync(join(pkgDir, "package.json"), "utf-8"));

const names = sortModuleNames(
  Object.keys(pkg.dependencies ?? {})
    .filter((dep) => dep.startsWith(PREFIX))
    .map((dep) => dep.slice(PREFIX.length)),
);

const lines = [
  "// WARNING: this file is auto-generated by codegen. Do not edit.",
  "",
  `export const MODULE_NAMES: string[] = ${JSON.stringify(names)};`,
  "",
  "export const moduleEntries = [",
  // std is excluded: @evmcrispr/core always loads it.
  ...names
    .filter((name) => name !== "std")
    .map(
      (name) =>
        `  { name: ${JSON.stringify(name)}, load: () => import(${JSON.stringify(PREFIX + name)}) },`,
    ),
  "];",
  "",
];

const outPath = join(pkgDir, "src/_generated.ts");
const content = lines.join("\n");

// Only write if content actually changed to avoid unnecessary filesystem
// events that trigger turbo watch / bun build --watch cascades.
if (!existsSync(outPath) || readFileSync(outPath, "utf-8") !== content) {
  writeFileSync(outPath, content);
  console.log(`codegen: wrote ${outPath}`);
} else {
  console.log(`codegen: ${outPath} up to date`);
}
