#!/usr/bin/env bun
/**
 * Generates src/_generated.ts (module registry) from this package's own
 * dependencies, so the registry can never drift from package.json.
 * The dependency list itself is kept in sync with the modules/ directory
 * by scripts/sync-modules.ts at the repo root.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { sortModuleNames } from "../src/order";

const PREFIX = "@evmcrispr/module-";
const pkgDir = resolve(import.meta.dirname, "..");
const pkg = JSON.parse(readFileSync(join(pkgDir, "package.json"), "utf-8"));

const names = sortModuleNames(
  Object.keys(pkg.dependencies ?? {})
    .filter((dep) => dep.startsWith(PREFIX))
    .map((dep) => dep.slice(PREFIX.length)),
);

/** Modules flagged `"experimental": true` in their package.json (layout
 *  guaranteed by scripts/sync-modules.ts). */
function isExperimental(name: string): boolean {
  const modulePkgPath = join(pkgDir, "../../modules", name, "package.json");
  if (!existsSync(modulePkgPath)) return false;
  try {
    return (
      JSON.parse(readFileSync(modulePkgPath, "utf-8")).experimental === true
    );
  } catch {
    return false;
  }
}

const experimentalNames = names.filter(isExperimental);

/** Chains a module ships in its literal-only `src/chains.ts`. Inlined here
 *  so hosts can list them (wallet networks, RPC config) without loading
 *  the module. */
function moduleChains(name: string): unknown[] {
  const chainsPath = join(pkgDir, "../../modules", name, "src/chains.ts");
  if (!existsSync(chainsPath)) return [];
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    return (require(chainsPath).chains ?? []) as unknown[];
  } catch {
    return [];
  }
}

const chainsByModule = new Map(
  names.map((name) => [name, moduleChains(name)] as const),
);
const allChains = [...chainsByModule.values()].flat();

const lines = [
  "// WARNING: this file is auto-generated by codegen. Do not edit.",
  "",
  `export const MODULE_NAMES: string[] = ${JSON.stringify(names)};`,
  "",
  `export const EXPERIMENTAL_MODULE_NAMES: string[] = ${JSON.stringify(experimentalNames)};`,
  "",
  "/** Chains declared by modules (their `src/chains.ts`), usable before any module loads. */",
  `export const moduleChains: ChainDef[] = ${JSON.stringify(allChains)};`,
  "",
  "export const moduleEntries = [",
  // std is excluded: @evmcrispr/core always loads it.
  ...names
    .filter((name) => name !== "std")
    .map((name) => {
      const chains = chainsByModule.get(name) ?? [];
      const extras = [
        experimentalNames.includes(name) ? ", experimental: true" : "",
        chains.length > 0 ? `, chains: ${JSON.stringify(chains)}` : "",
      ].join("");
      return `  { name: ${JSON.stringify(name)}, load: () => import(${JSON.stringify(PREFIX + name)})${extras} },`;
    }),
  "];",
  "",
];
lines.splice(1, 0, "", 'import type { ChainDef } from "@evmcrispr/core";');

const outPath = join(pkgDir, "src/_generated.ts");
const content = lines.join("\n");

// Only write if content actually changed to avoid unnecessary filesystem
// events that trigger turbo watch / bun build --watch cascades.
if (!existsSync(outPath) || readFileSync(outPath, "utf-8") !== content) {
  writeFileSync(outPath, content);
  console.log(`codegen: wrote ${outPath}`);
} else {
  console.log(`codegen: ${outPath} up to date`);
}
