/** Regenerate production verification hashes from the pinned test artifacts. */
import { writeFileSync } from "node:fs";
import { keccak256 } from "viem";
import {
  ASSERTIONS_RUNTIME_BYTECODE,
  COLLECTIONS_RUNTIME_BYTECODE,
  EXPRESSIONS_RUNTIME_BYTECODE,
  OPERATIONS_RUNTIME_BYTECODE,
} from "../packages/test-utils/src/onchain/assertions-bytecode";

const entries = {
  CORE_ADDRESS: ASSERTIONS_RUNTIME_BYTECODE,
  OPERATIONS_ADDRESS: OPERATIONS_RUNTIME_BYTECODE,
  COLLECTIONS_ADDRESS: COLLECTIONS_RUNTIME_BYTECODE,
  EXPRESSIONS_ADDRESS: EXPRESSIONS_RUNTIME_BYTECODE,
};
writeFileSync(
  new URL("../packages/sdk/src/onchain/dependency-hashes.ts", import.meta.url),
  `// Generated by scripts/sync-smart-dependency-hashes.ts.\nimport { ${Object.keys(entries).join(", ")} } from "./addresses";\nimport type { Address, Hex } from "viem";\nexport const SMART_DEPENDENCY_HASHES: Record<Address, Hex> = {\n${Object.entries(
    entries,
  )
    .map(
      ([name, code]) =>
        `  [${name}.toLowerCase() as Address]: "${keccak256(code)}",`,
    )
    .join("\n")}\n};\n`,
);
