/**
 * Vendors the RUNTIME bytecode of the Assertions core and the Operators
 * vocabulary into a committed test fixture.
 *
 * Integration tests need the two contracts on the anvil fork to execute a
 * compiled operand (`Assertions.resolve`). The contracts live in a separate
 * repo whose build artifacts are gitignored and not reachable at test time,
 * so the runtime code is copied in here instead.
 *
 * Runtime, not creation, bytecode: `anvil_setCode` installs runtime code, and
 * because both contracts have no constructor, no storage, no immutables and no
 * linked libraries, setting the runtime code IS a complete and faithful
 * deployment — at any address. (`website/scripts/export-deploy-artifact.mjs`
 * in the contracts repo exports the CREATION bytecode for the deploy path;
 * different consumer, different artifact, both are needed.)
 *
 * Run by hand after changing a contract; wired into no turbo task, because a
 * plain EVMcrispr checkout has no contracts repo beside it:
 *
 *   bun scripts/sync-assertions-bytecode.ts
 *   ASSERTIONS_ARTIFACTS=/path/to/artifacts bun scripts/sync-assertions-bytecode.ts
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { keccak256 } from "viem";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");

/** The contracts repo is the grandparent when vendored at `website/.evmcrispr`. */
const artifactsDir =
  process.env.ASSERTIONS_ARTIFACTS ?? resolve(repoRoot, "../../artifacts");

const OUTPUT = join(
  repoRoot,
  "packages/test-utils/src/onchain/assertions-bytecode.ts",
);

const CONTRACTS = [
  {
    name: "Assertions",
    path: "contracts/Assertions.sol/Assertions.json",
    prefix: "ASSERTIONS",
    label: "Assertions core",
  },
  {
    name: "Operators",
    path: "contracts/Operators.sol/Operators.json",
    prefix: "OPERATORS",
    label: "Operators vocabulary",
  },
  {
    // The contracts repo's own test mock, vendored for the same reason as
    // the core: revert-probe integration tests need a target that reverts
    // with KNOWN custom errors (InsufficientBalance, Unauthorized,
    // Redirect(address,address[])) and known reasons. Unlike the core it
    // has one storage slot (storedValue = 42) — the installer sets it.
    name: "MockTarget",
    path: "contracts/tests/Mocks.sol/MockTarget.json",
    prefix: "MOCK_TARGET",
    label: "MockTarget revert fixture",
  },
] as const;

function die(message: string): never {
  console.error(`sync-assertions-bytecode: ${message}`);
  process.exit(2);
}

if (!existsSync(artifactsDir)) {
  die(
    `no contracts artifacts at ${artifactsDir}.\n` +
      `  This script vendors bytecode from the Assertions contracts repo, which is\n` +
      `  not part of an EVMcrispr checkout. Build it there (\`pnpm hardhat compile\`)\n` +
      `  or point ASSERTIONS_ARTIFACTS at an existing artifacts directory.`,
  );
}

const parts: string[] = [];

for (const { name, path: artifactPath, prefix, label } of CONTRACTS) {
  const path = join(artifactsDir, artifactPath);
  if (!existsSync(path)) die(`missing artifact ${path}`);

  const artifact = JSON.parse(readFileSync(path, "utf8"));
  const runtime: string = artifact.deployedBytecode;

  if (typeof runtime !== "string" || !runtime.startsWith("0x")) {
    die(`${name}: artifact has no deployedBytecode`);
  }
  // A contract with immutables or unlinked libraries carries placeholders in
  // its runtime code that only a real deployment fills in, so setCode would
  // install something subtly broken. Both contracts are stateless today; if
  // that ever changes, this must fail rather than vendor a lie.
  for (const [field, value] of [
    ["immutableReferences", artifact.immutableReferences],
    ["deployedLinkReferences", artifact.deployedLinkReferences],
  ] as const) {
    if (value && Object.keys(value).length > 0) {
      die(
        `${name}: ${field} is non-empty, so its runtime bytecode is not ` +
          `position-independent and anvil_setCode would not be a faithful install`,
      );
    }
  }

  const bytes = (runtime.length - 2) / 2;
  console.log(`${name}: ${bytes} bytes of runtime bytecode`);

  parts.push(
    `/** keccak256 of the ${label}'s runtime bytecode. The contracts repo's\n` +
      ` *  export script compares against this to detect that the fixture went\n` +
      ` *  stale — nothing inside this repo can see the contracts to check. */\n` +
      `export const ${prefix}_RUNTIME_HASH =\n  "${keccak256(runtime as `0x${string}`)}" as const;\n\n` +
      `/** Runtime bytecode of the ${label} (${bytes} bytes). */\n` +
      `export const ${prefix}_RUNTIME_BYTECODE =\n  "${runtime}" as const;`,
  );
}

const header = `// Generated by scripts/sync-assertions-bytecode.ts — do not edit by hand.
//
// Runtime bytecode of the Assertions core and the Operators vocabulary,
// vendored from the contracts repo so integration tests can install them on
// the anvil fork with \`anvil_setCode\` and actually EXECUTE compiled operands.
//
// Both contracts have no constructor, no storage, no immutables and no linked
// libraries (the generator asserts this), so setting the runtime code is a
// complete install at any address — no CREATE2 dance, no funded deployer.
//
// See packages/test-utils/src/onchain/install.ts for the installer.
`;

writeFileSync(OUTPUT, `${header}\n${parts.join("\n\n")}\n`);
console.log(`wrote ${OUTPUT}`);
